// user context
const OPEN_SIDEBAR = "OPEN_SIDEBAR";
const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
const TOGGLE_NAV_MODAL = "TOGGLE_NAV_MODAL";
const CLOSE_NAV_MODAL = "CLOSE_NAV_MODAL";
const BEGIN_REGISTER = "BEGIN_REGISTER";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_ERROR = "REGISTER_SUCCESS";
const BEGIN_LOGIN = "BEGIN_LOGIN";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_ERROR = "LOGIN_SUCCESS";
const LOGOUT_USER = "LOGOUT_USER";
const BEGIN_UPDATE = "BEGIN_UPDATE";
const UPDATE_SUCCESS = "UPDATE_SUCCESS";
const UPDATE_ERROR = "UPDATE_SUCCESS";

// financials context
const BEGIN_ADD_ENTRY = "BEGIN_ADD_ENTRY";
const ADD_ENTRY_SUCCESS = "ADD_ENTRY_SUCCESS";
const ADD_ENTRY_ERROR = "ADD_ENTRY_ERROR";
const BEGIN_FINANCIALS_FETCH = "BEGIN_FINANCIALS_FETCH";
const FINANCIALS_FETCH_SUCCESS = "FINANCIALS_FETCH_SUCCESS";
const FINANCIALS_FETCH_ERROR = "FINANCIALS_FETCH_ERROR";
const HANDLE_ENTRY_CHANGE = "HANDLE_ENTRY_CHANGE";
const CLEAR_ENTRY_VALUES = "CLEAR_ENTRY_VALUES";
const SET_EDIT_FINANCIAL = "SET_EDIT_FINANCIAL";
const BEGIN_FINANCIAL_EDIT = "BEGIN_FINANCIAL_EDIT";
const FINANCIAL_EDIT_SUCCESS = "FINANCIAL_EDIT_SUCCESS";
const FINANCIAL_EDIT_ERROR = "FINANCIAL_EDIT_ERROR";
const HANDLE_FILTERS_CHANGE = "HANDLE_FILTERS_CHANGE";
const CLEAR_FILTERS = "CLEAR_FILTERS";
const SET_PAGE = "SET_PAGE";
const SET_PREV_PAGE = "SET_PREV_PAGE";
const SET_NEXT_PAGE = "SET_NEXT_PAGE";

export {
  CLOSE_SIDEBAR,
  OPEN_SIDEBAR,
  TOGGLE_NAV_MODAL,
  CLOSE_NAV_MODAL,
  BEGIN_REGISTER,
  REGISTER_SUCCESS,
  REGISTER_ERROR,
  BEGIN_LOGIN,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  LOGOUT_USER,
  BEGIN_UPDATE,
  UPDATE_SUCCESS,
  UPDATE_ERROR,
  BEGIN_ADD_ENTRY,
  ADD_ENTRY_SUCCESS,
  ADD_ENTRY_ERROR,
  BEGIN_FINANCIALS_FETCH,
  FINANCIALS_FETCH_SUCCESS,
  FINANCIALS_FETCH_ERROR,
  HANDLE_ENTRY_CHANGE,
  CLEAR_ENTRY_VALUES,
  SET_EDIT_FINANCIAL,
  BEGIN_FINANCIAL_EDIT,
  FINANCIAL_EDIT_SUCCESS,
  FINANCIAL_EDIT_ERROR,
  HANDLE_FILTERS_CHANGE,
  CLEAR_FILTERS,
  SET_PAGE,
  SET_PREV_PAGE,
  SET_NEXT_PAGE,
};
